package GUI;

import Controller.ServerManager;
import Interfaces.ChatServer;
import Server.ChatServerImpl;
import java.net.MalformedURLException;

import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;

public class ServerFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerFrame.class.getName());

    /**
     * Creates new form ServerFrame
     */
    public ServerFrame() {
        initComponents();
        startServer();
    }

    public void addLog(String message) {

        txtLog.append(
                message + "\n"
        );
    }

    public void updateClients(int total) {

        lblClientsCount.setText(
                String.valueOf(total)
        );
    }

    private void startServer() {

        try {

            int port = 1234;

            System.setProperty(
                    "java.rmi.server.hostname",
                    "192.168.0.160"
            );

            LocateRegistry.createRegistry(port);

            ServerManager manager
                    = new ServerManager(this);

            ChatServer server
                    = new ChatServerImpl(manager);

            Naming.rebind(
                    "//192.168.0.160:"
                    + port
                    + "/ChatService",
                    server
            );

            addLog("Chat RMI Server Ready");
            System.out.println("Chat RMI Server Ready");

        } catch (MalformedURLException | RemoteException e) {

            addLog(
                    "ERROR: "
                    + e.getMessage()
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblClients = new javax.swing.JLabel();
        lblClientsCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chat RMI Server");
        getContentPane().add(lblTitle, java.awt.BorderLayout.PAGE_START);

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        lblClients.setText("Clients:");
        jPanel1.add(lblClients);

        lblClientsCount.setText("0");
        jPanel1.add(lblClientsCount);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClients;
    private javax.swing.JLabel lblClientsCount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
