package windows;

/**
 *
 * @author dante
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statePanel = new javax.swing.JPanel();
        lblProducers = new javax.swing.JLabel();
        lblProducersNumb = new javax.swing.JLabel();
        lblConsumers = new javax.swing.JLabel();
        lblConsumersNumb = new javax.swing.JLabel();
        lblBuffer = new javax.swing.JLabel();
        lblBufferNumb = new javax.swing.JLabel();
        controllerPanels = new javax.swing.JPanel();
        btnAddProducer = new javax.swing.JButton();
        btnAddConsumer = new javax.swing.JButton();
        btnDeleteProducer = new javax.swing.JButton();
        btnDeleteConsumer = new javax.swing.JButton();
        bufferPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Cell0 = new javax.swing.JPanel();
        Cell1 = new javax.swing.JPanel();
        Cell2 = new javax.swing.JPanel();
        cell3 = new javax.swing.JPanel();
        Cell4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Cell5 = new javax.swing.JPanel();
        Cell6 = new javax.swing.JPanel();
        Cell7 = new javax.swing.JPanel();
        Cell8 = new javax.swing.JPanel();
        Cell9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        statePanel.setLayout(new java.awt.GridLayout(1, 6));

        lblProducers.setText("Producers:");
        statePanel.add(lblProducers);

        lblProducersNumb.setText("0");
        statePanel.add(lblProducersNumb);

        lblConsumers.setText("Consumers:");
        statePanel.add(lblConsumers);

        lblConsumersNumb.setText("0");
        statePanel.add(lblConsumersNumb);

        lblBuffer.setText("Buffer:");
        statePanel.add(lblBuffer);

        lblBufferNumb.setText("0");
        statePanel.add(lblBufferNumb);

        getContentPane().add(statePanel, java.awt.BorderLayout.PAGE_START);

        controllerPanels.setLayout(new java.awt.GridLayout(2, 2));

        btnAddProducer.setText("Add Producer");
        controllerPanels.add(btnAddProducer);

        btnAddConsumer.setText("Add Consumer");
        controllerPanels.add(btnAddConsumer);

        btnDeleteProducer.setText("Delete Producer");
        controllerPanels.add(btnDeleteProducer);

        btnDeleteConsumer.setText("Delete Consumer");
        controllerPanels.add(btnDeleteConsumer);

        getContentPane().add(controllerPanels, java.awt.BorderLayout.PAGE_END);

        bufferPanel.setPreferredSize(new java.awt.Dimension(600, 200));
        bufferPanel.setLayout(new java.awt.GridLayout(2, 5));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 15));

        Cell0.setBackground(new java.awt.Color(255, 255, 255));
        Cell0.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell0Layout = new javax.swing.GroupLayout(Cell0);
        Cell0.setLayout(Cell0Layout);
        Cell0Layout.setHorizontalGroup(
            Cell0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell0Layout.setVerticalGroup(
            Cell0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel1.add(Cell0);

        Cell1.setBackground(new java.awt.Color(255, 255, 255));
        Cell1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell1Layout = new javax.swing.GroupLayout(Cell1);
        Cell1.setLayout(Cell1Layout);
        Cell1Layout.setHorizontalGroup(
            Cell1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell1Layout.setVerticalGroup(
            Cell1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel1.add(Cell1);

        Cell2.setBackground(new java.awt.Color(255, 255, 255));
        Cell2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell2Layout = new javax.swing.GroupLayout(Cell2);
        Cell2.setLayout(Cell2Layout);
        Cell2Layout.setHorizontalGroup(
            Cell2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell2Layout.setVerticalGroup(
            Cell2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel1.add(Cell2);

        cell3.setBackground(new java.awt.Color(255, 255, 255));
        cell3.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout cell3Layout = new javax.swing.GroupLayout(cell3);
        cell3.setLayout(cell3Layout);
        cell3Layout.setHorizontalGroup(
            cell3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        cell3Layout.setVerticalGroup(
            cell3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel1.add(cell3);

        Cell4.setBackground(new java.awt.Color(255, 255, 255));
        Cell4.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell4Layout = new javax.swing.GroupLayout(Cell4);
        Cell4.setLayout(Cell4Layout);
        Cell4Layout.setHorizontalGroup(
            Cell4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell4Layout.setVerticalGroup(
            Cell4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel1.add(Cell4);

        bufferPanel.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 15, 15));

        Cell5.setBackground(new java.awt.Color(255, 255, 255));
        Cell5.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell5Layout = new javax.swing.GroupLayout(Cell5);
        Cell5.setLayout(Cell5Layout);
        Cell5Layout.setHorizontalGroup(
            Cell5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell5Layout.setVerticalGroup(
            Cell5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel2.add(Cell5);

        Cell6.setBackground(new java.awt.Color(255, 255, 255));
        Cell6.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell6Layout = new javax.swing.GroupLayout(Cell6);
        Cell6.setLayout(Cell6Layout);
        Cell6Layout.setHorizontalGroup(
            Cell6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell6Layout.setVerticalGroup(
            Cell6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel2.add(Cell6);

        Cell7.setBackground(new java.awt.Color(255, 255, 255));
        Cell7.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell7Layout = new javax.swing.GroupLayout(Cell7);
        Cell7.setLayout(Cell7Layout);
        Cell7Layout.setHorizontalGroup(
            Cell7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell7Layout.setVerticalGroup(
            Cell7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel2.add(Cell7);

        Cell8.setBackground(new java.awt.Color(255, 255, 255));
        Cell8.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell8Layout = new javax.swing.GroupLayout(Cell8);
        Cell8.setLayout(Cell8Layout);
        Cell8Layout.setHorizontalGroup(
            Cell8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell8Layout.setVerticalGroup(
            Cell8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel2.add(Cell8);

        Cell9.setBackground(new java.awt.Color(255, 255, 255));
        Cell9.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Cell9Layout = new javax.swing.GroupLayout(Cell9);
        Cell9.setLayout(Cell9Layout);
        Cell9Layout.setHorizontalGroup(
            Cell9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        Cell9Layout.setVerticalGroup(
            Cell9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jPanel2.add(Cell9);

        bufferPanel.add(jPanel2);

        getContentPane().add(bufferPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cell0;
    private javax.swing.JPanel Cell1;
    private javax.swing.JPanel Cell2;
    private javax.swing.JPanel Cell4;
    private javax.swing.JPanel Cell5;
    private javax.swing.JPanel Cell6;
    private javax.swing.JPanel Cell7;
    private javax.swing.JPanel Cell8;
    private javax.swing.JPanel Cell9;
    private javax.swing.JButton btnAddConsumer;
    private javax.swing.JButton btnAddProducer;
    private javax.swing.JButton btnDeleteConsumer;
    private javax.swing.JButton btnDeleteProducer;
    private javax.swing.JPanel bufferPanel;
    private javax.swing.JPanel cell3;
    private javax.swing.JPanel controllerPanels;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBuffer;
    private javax.swing.JLabel lblBufferNumb;
    private javax.swing.JLabel lblConsumers;
    private javax.swing.JLabel lblConsumersNumb;
    private javax.swing.JLabel lblProducers;
    private javax.swing.JLabel lblProducersNumb;
    private javax.swing.JPanel statePanel;
    // End of variables declaration//GEN-END:variables
}
