package vowelcounter.windows;

import javax.swing.SwingUtilities;
import model.VowelResult;

/**
 *
 * @author dante
 */
public class StatsWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatsWindow.class.getName());

    public StatsWindow() {
        initComponents();
    }

    // Called after each file finishes — accumulates stats
    // synchronized because concurrent mode calls this from multiple threads
    public synchronized void updateStats(VowelResult result) {
        // Accumulate counts — add to existing values
        SwingUtilities.invokeLater(() -> {
            lblACount.setText(String.valueOf(
                    parseLong(lblACount.getText()) + result.getCountA()));
            lblECount.setText(String.valueOf(
                    parseLong(lblECount.getText()) + result.getCountE()));
            lblICount.setText(String.valueOf(
                    parseLong(lblICount.getText()) + result.getCountI()));
            lblOCount.setText(String.valueOf(
                    parseLong(lblOCount.getText()) + result.getCountO()));
            lblUCount.setText(String.valueOf(
                    parseLong(lblUCount.getText()) + result.getCountU()));
            lblAccCount.setText(String.valueOf(
                    parseLong(lblAccCount.getText()) + result.getCountAccented()));

            // Update total
            long total = parseLong(lblTotalCount.getText()) + result.getTotal();
            lblTotalCount.setText(String.valueOf(total));

            // Update most frequent — recalculate from current totals
            updateMostFrequent();
        });
    }

// Reset all stats to 0 — called before a new run
    public void clearStats() {
        SwingUtilities.invokeLater(() -> {
            lblACount.setText("0");
            lblECount.setText("0");
            lblICount.setText("0");
            lblOCount.setText("0");
            lblUCount.setText("0");
            lblAccCount.setText("0");
            lblTotalCount.setText("0");
            lblMostFreqCount.setText("-");
        });
    }

// == Private helpers =========================================
// Safe parse — returns 0 if label has "-" or is not a number
    private long parseLong(String text) {
        try {
            return Long.parseLong(text);
        } catch (NumberFormatException e) {
            return 0; // "-" or empty — treat as 0
        }
    }

// Recalculate most frequent from current label values
    private void updateMostFrequent() {
        long a = parseLong(lblACount.getText());
        long e = parseLong(lblECount.getText());
        long i = parseLong(lblICount.getText());
        long o = parseLong(lblOCount.getText());
        long u = parseLong(lblUCount.getText());

        long max = Math.max(a, Math.max(e, Math.max(i, Math.max(o, u))));
        if (max == 0) {
            lblMostFreqCount.setText("-");
            return;
        }

        if (max == a) {
            lblMostFreqCount.setText("A");
        } else if (max == e) {
            lblMostFreqCount.setText("E");
        } else if (max == i) {
            lblMostFreqCount.setText("I");
        } else if (max == o) {
            lblMostFreqCount.setText("O");
        } else {
            lblMostFreqCount.setText("U");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblTotalCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMostFreqCount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblA = new javax.swing.JLabel();
        lblACount = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblECount = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblICount = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        lblOCount = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        lblUCount = new javax.swing.JLabel();
        lblAccented = new javax.swing.JLabel();
        lblAccCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setText("Vocal Statistics");
        lbTitle.setToolTipText("");
        getContentPane().add(lbTitle, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        lblTotal.setText("Total vowels:");
        jPanel2.add(lblTotal);

        lblTotalCount.setText("0");
        jPanel2.add(lblTotalCount);

        jLabel3.setText("Most frequent:");
        jPanel2.add(jLabel3);

        lblMostFreqCount.setText("-");
        jPanel2.add(lblMostFreqCount);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(3, 4));

        lblA.setText("A:");
        jPanel1.add(lblA);

        lblACount.setText("0");
        jPanel1.add(lblACount);

        lblE.setText("E:");
        jPanel1.add(lblE);

        lblECount.setText("0");
        jPanel1.add(lblECount);

        lblI.setText("I:");
        jPanel1.add(lblI);

        lblICount.setText("0");
        jPanel1.add(lblICount);

        lblO.setText("O:");
        jPanel1.add(lblO);

        lblOCount.setText("0");
        jPanel1.add(lblOCount);

        lblU.setText("U:");
        jPanel1.add(lblU);

        lblUCount.setText("0");
        jPanel1.add(lblUCount);

        lblAccented.setText("Accented:");
        jPanel1.add(lblAccented);

        lblAccCount.setText("0");
        jPanel1.add(lblAccCount);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StatsWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblACount;
    private javax.swing.JLabel lblAccCount;
    private javax.swing.JLabel lblAccented;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblECount;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblICount;
    private javax.swing.JLabel lblMostFreqCount;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblOCount;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalCount;
    private javax.swing.JLabel lblU;
    private javax.swing.JLabel lblUCount;
    // End of variables declaration//GEN-END:variables
}
